### ISSUE TITLE
Strange Shadow in upper right corner of screen

### ISSUE THREAD

**Issue by Horonelius** [freaktechnik/justintv-stream-notifications#465] opened 2019-02-12 07:34 UTC
## System Info

- *Operating System*: Windows 10 (64-bit)
- *Firefox Version*: 65.0
- *Extension Version*: 3.11.1

Whenever I start up Firefox the past several months, I usually notice a shadow in the upper right corner of my screen, just to the left of the minimize button, and about the length of the "stream is live" popup notification. Clicking on it ends up directing me to a stream.

![thatshadow](https://user-images.githubusercontent.com/47553585/52619326-02809080-2e67-11e9-89a3-2251adf61d1b.png)

Originally I thought it was the backlight in my monitor going or something, but I only notice it when I start up Firefox. Moving the window around leaves the shadow in the same spot relative to the screen, which leads me to believe that the notification window that I can't see is actually hanging out just above the screen, casting a shadow, which can be interacted with.  After the notification window WOULD disappear on its own, the shadow disappears. This doesn't occur if a user I have in the plugin goes active AFTER starting the browser, those notifications show up just fine. But if there is already one or more ongoing when I start Firefox, that shadow shows up, with no notification that I can see.

I've had this issue on multiple versions of Firefox, with a clean profile and nothing but this plugin installed.

**Comment by freaktechnik** [comment] 2019-02-12 09:43
Yeah, as far as I know this is a placement issue of notifications by Firefox. Duplicate of #312

**Closed by freaktechnik** 2019-02-12 09:43 UTC
