### ISSUE TITLE
Auto-update channel status doesn't seem to work

### ISSUE THREAD

**Issue by Redthirst** [freaktechnik/justintv-stream-notifications#137] opened 2016-02-03 10:08 UTC
As of the last update, it seems like channel status doesn't update. This means that when channel goes offline it will remain in your list of online channels until you manualy update its status through context menu.

**Comment by freaktechnik** [comment] 2016-02-03 12:25
I've already had a report of this bug. Disabling hosting (`twitch_showHosting` as explained on http://streamnotifier.ch/aboutconfig/) will most likely fix this or restarting Firefox. However it is possible that some of the data the extension stored is damaged, and if so, you will have to remove and readd everything (you can <kbd>Shift</kbd> and <kbd>Delete</kbd> an account to remove all the channels it follows).

I have sadly so far not been able to reproduce this issue myself. It is possibly fixed with 23705b766ef2794c119420179694163b94da844c but I want to add additional error-reporting infrastructure (essentially a manual data dump) before releasing it.

If you encounter this issue next time, please open the Browser Console from the Developer Tools menu, trigger a manual update and paste the errors that appear (if any).

Just out of curiosity, could you provide all the channels you have added? One way to get them is to run `[...document.querySelectorAll('option span')].map((s) => s.textContent).join(",")` in the Web Developer Console. If all your channels are the favorites of a user you added, you can also just specify that user.
Further what refresh interval do you use?

**Comment by freaktechnik** [comment] 2016-02-03 12:29
One known follow up error (so an error caused by this but not the error causing it) is
```
justintv-stream-notifications:TypeError: channel.url is undefined                     core.js:106
Stack-Trace:
Notifier.prototype.sendNotification@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/notifier.js:33:12
onChannelupdated@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/main.js:77:13
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
setup/this._list<.onChannelupdated@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/channel/controller.js:153:17
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
ChannelList.prototype.setChannel</req.onsuccess/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-z2wajbefd5dtcgsj70eq6uaqql4-at-jetpack/lib/channel/list.js:288:13
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1
```
which will make the affected channels broken until they go live again or are individually manually refreshed. This is also why clicking on a "zombie" channel doesn't open a tab.

**Comment by Redthirst** [comment] 2016-02-03 12:59
Hm, that's weird. A stream I was watching just ended, but it was correctly removed from online list.

Two things that separate it from other channels I follow through add-on:
1. I added it after the latest update.
2. It's a small stream with only a handful of viewers(doubt it has anything to do with it).

First option sounds as a likely reason why it is updates correctly. Which means that it only affects channels that I had added before the update.

**Comment by freaktechnik** [comment] 2016-02-03 13:31
Yes it seems indeed to be an upgrade issue. But I cannot find what's causing it, since I'd like to fix it with the next version, if possible.

**Comment by freaktechnik** [comment] 2016-02-03 13:34
I think I know what's up. And it's going to be fun to fix it...

**Comment by freaktechnik** [comment] 2016-02-03 14:38
I've found the issue causing it. I've published a [beta version](https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/?page=1#version-3.2.2-pre1) right now, which should fix it (it should also fixup existing data) and will submit a full version to review tonight.
@Redthirst It'd be much appreciated if you could try out the beta version and confirm if it fixes the issue for you. You'll have to manually go back to the release version, but I'll post here again when the release is available on AMO.

**Comment by Redthirst** [comment] 2016-02-03 15:49
I can try, but I'm not sure I will be able to reproduce it right now. Most of the streamers that start streaming at this time contiue to do so after I go to sleep. However, I can try.

**Comment by Nhoise** [comment] 2016-02-03 20:02
I've had channels stay 'online' as well while they were offline with 3.2.1 but I was just watching Deuceler on Twitch and when he went offline his status got updated properly and he disappeared from the online list.
So I'm pretty sure it's now fixed with 3.2.2pre1, but will keep an eye on it.

**Comment by freaktechnik** [comment] 2016-02-03 21:02
3.2.2 is now in the queue for getting reviewed: https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/?page=1#version-3.2.2

**Comment by Redthirst** [comment] 2016-02-03 21:54
Ok, the tournament stream just ended, and its status got properly updated. Seems like the next version did fix it.

**Comment by freaktechnik** [comment] 2016-02-04 00:17
Niceè Thanks for the help!

**Closed by freaktechnik** 2016-02-04 00:17 UTC
Labels: bug
